services:
  cesbin-server:
    container_name: cesbin-server
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/project/src
      - ./pastes:/project/pastes
    env_file:
      - .env
    ports:
      - "8000:8000"