"""Create format table

Revision ID: da51f2ef8399
Revises: a73f2e8e3068
Create Date: 2024-11-16 21:16:41.958945

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'da51f2ef8399'
down_revision: Union[str, None] = 'a73f2e8e3068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Format',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('Paste', sa.Column('format_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Paste', 'Format', ['format_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Paste', type_='foreignkey')
    op.drop_column('Paste', 'format_id')
    op.drop_table('Format')
    # ### end Alembic commands ###
