"""Init Paste and Period

Revision ID: af4a9aca3f87
Revises: 
Create Date: 2024-11-16 16:57:20.989962

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af4a9aca3f87"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Paste",
        sa.Column("paste_path", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expire_at", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paste_path"),
    )
    op.create_table(
        "Period",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("duration", sa.Interval(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Period")
    op.drop_table("Paste")
    # ### end Alembic commands ###
