"""Create relationship between pastes and formats

Revision ID: 746749d19941
Revises: 3670b35ffd2c
Create Date: 2025-02-13 23:04:47.887869

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '746749d19941'
down_revision: Union[str, None] = '3670b35ffd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastes', sa.Column('format_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pastes', 'formats', ['format_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pastes', type_='foreignkey')
    op.drop_column('pastes', 'format_id')
    # ### end Alembic commands ###
