"""Update Paste

Revision ID: 8218e6ab4300
Revises: 518b8353f985
Create Date: 2024-06-10 17:22:30.510069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8218e6ab4300"
down_revision: Union[str, None] = "518b8353f985"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Paste", sa.Column("title", sa.String(length=20), nullable=False))
    op.add_column("Paste", sa.Column("expire_at", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Paste", "expire_at")
    op.drop_column("Paste", "title")
    # ### end Alembic commands ###
