"""paste_path in Paste model

Revision ID: 834c634bd367
Revises: 88c31e54cfed
Create Date: 2024-06-29 21:02:04.361072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834c634bd367'
down_revision: Union[str, None] = '88c31e54cfed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Paste', sa.Column('paste_path', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Paste', 'paste_path')
    # ### end Alembic commands ###
