"""Update Paste model

Revision ID: 88c31e54cfed
Revises: 8218e6ab4300
Create Date: 2024-06-29 20:35:51.547622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c31e54cfed'
down_revision: Union[str, None] = '8218e6ab4300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Paste', 'title')
    op.drop_column('Paste', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Paste', sa.Column('text', sa.VARCHAR(), nullable=False))
    op.add_column('Paste', sa.Column('title', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
