"""Edit id

Revision ID: c519c8dd3bf7
Revises: 
Create Date: 2024-10-05 11:46:37.554987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c519c8dd3bf7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Period',
    sa.Column('name', sa.String(length=4), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Paste',
    sa.Column('paste_path', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['Period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Paste')
    op.drop_table('Period')
    # ### end Alembic commands ###
